### PR TITLE
Modified hook to implement template_preprocess_HOOK()

### PR DESCRIPTION
**Pull request by nmader**
**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-1071

# What does this Pull Request do?

This pull request ensures that when a function in this module implements hook_theme() that the template_preprocess hook is called to allow overriding variables further down the processing chain.

# What's new?

The function name has been changed to begin with ‘template’ instead of islandora_solution_pack_audio.

# Interested parties

@Islandora/7-x-1-x-committers

### CODE REVIEW

**Review by DiegoPino — APPROVED** [review]

**Comment by DiegoPino** [comment]
@nmader are there other pending ones? I closed that Jira ticket, should I open it again?

**Comment by nmader** [comment]
@DiegoPino, Yes, that's probably a good idea. Unfortunately it looks like I missed 4 of them. I'm going back through them all now.

**Comment by DiegoPino** [comment]
@nmader ping when you have all pulls ready to review. Since they all look the same, the merge should happen quickly. Thanks

**Comment by willtp87** [comment]
Changes seem good to me.

**Pull request merged**
