### PR TITLE
OBJ fallback

### PR DESCRIPTION
**Pull request by qadan**
**Jira:** https://jira.duraspace.org/browse/ISLANDORA-1549
# What does this Pull Request do?

Adds an administrator-toggleable fallback to the OBJ datastream if the PROXY_MP3 doesn't exist and the OBJ can be played by the browser.
# How should this be tested?

This should be tested with several different OBJ datastreams, including ones that are invalid for playback in the browser. There's some involved logic here, but the order of operations should go:
- If the PROXY_MP3 datastream is present, this should be used as the DSID.
- If no PROXY_MP3 datastream is present, then
- If the new OBJ fallback flag added in this PR is set, and an OBJ datastream exists, and the OBJ datastream is an audio/mp4 or audio/mpeg datastream, then OBJ should be used as the DSID.
- If the chosen datastream is accessible by the current user, the viewer should be loaded and the datastream should be used for playback.
- If no datastream is valid, no viewer should be loaded.
# Background context:

We do a similar thing with Islandora Video Solution Pack; it makes sense not to generate and store superfluous datastreams if the original upload is suitable for playback.
# Screenshots (if appropriate)
## Before Screenshot

Before Screenshot
After Screenshot
# Additional Notes:
- **Does this change require documentation to be updated?** Yep! README should be up to date.
- **Does this change add any new dependencies?** Nope, it's all right in the module.
- **Does this change require any other modifications to be made to the repository (ie. Regeneration activity, etc.)?** No, this is independent of the repository.
- **Could this change impact execution of existing code?** I don't believe so.

**Tagging:** @Islandora/7-x-1-x-committers plus component manager @rosiel 

---

QA Dan
_Developer_
**[discoverygarden inc.](http://www.discoverygarden.ca) | Managing Digital Content**

### CODE REVIEW

**Comment by willtp87** [comment]
This pull looks good to me.

---

William Panting
_Developer_
_[discoverygarden inc.](http://www.discoverygarden.ca) | Managing Digital Content_

**Comment by mitchmac** [comment]
With no comments to the contrary, it seems like this can be merged?

**Comment by ryantownshend** [comment]
To sum my notes from internal QA

Ingested new audio object with mp3.
Confirmed audio in JW player on object detail.
Deleted PROXY_MP3 datastream

PROXY_MP3 datastream is indeed missing.
JW Player played the sample anyway.
Op Success.

**Comment by mitchmac** [comment]
Thank you @ruebot

**Comment by rosiel** [comment]
Works great in VideoJS.

**Pull request merged**
