### PR TITLE
Update audio solution pack for new codesniffs.

### PR DESCRIPTION
**Pull request by jonathangreen**
## JIRA Ticket

No JIRA ticket, but this is based off of the work here:
https://github.com/Islandora/islandora/pull/714

## What does this Pull Request do?

Now that the new code sniffer code is merged into core, each module needs to be updated to use the new sniffs. 

## What's new?

Updates the code to be compliant with the new code sniffer sniffs.

## How should this be tested?

Should be no functional change to the code, just code style.

## Interested parties

I'm the maintainer on this module, so I'll need a review from someone else.
@whikloj @Islandora/7-x-1-x-committers

### CODE REVIEW

**Comment by jonathangreen** [comment]
For some reason this isn't running the "Islandora Audio" tests, its actually running the Islandora ones. Need to look more into it.

**Comment by DiegoPino** [comment]
@jonathangreen i think this $1 https://github.com/Islandora/islandora/blob/7.x/tests/scripts/run_tests.sh#L5 should be wrapped around quotes and/or escaped somehow?. Currently when evaluated that outputs basically 

`php scripts/run-tests.sh --php `phpenv which php` --url http://localhost:8081 --verbose Islandora Audio`

Which for PHP is
`php scripts/run-tests.sh --php `phpenv which php` --url http://localhost:8081 --verbose Islandora` 

Its a tiny error that carried over since we never tested this in other modules (i guess?)

Or maybe its just me...

**Comment by jonathangreen** [comment]
🙌🏻 this is passing now

**Review by DiegoPino — APPROVED** [review]
kool kat

**Comment by DiegoPino** [comment]
24 hours to go. Will be watching. Good work @jonathangreen

**Comment by whikloj** [comment]
@DiegoPino this is ready for you to merge.

**Comment by DiegoPino** [comment]
Longest 24 hours ever! Thanks,merged

**Pull request merged**
